language: cpp
addons:
    apt:
      packages:
        - swig
        - gfortran
        - libfftw3-dev
        - libcfitsio3-dev
        - libmuparser-dev
        - python-dev
        - python-numpy
        - python-setuptools
        - python3-setuptools
        - python3-dev
        - cmake
        - libhdf5-serial-dev
        - python-matplotlib
        - python3-matplotlib
        - python-scipy
        - python3-scipy
        - libiomp5
        - libiomp-dev
        - doxygen
        - graphviz
cache:
  directories:
    - $HOME/.cache
matrix:
  include:
    - os : linux
      dist: trusty
      compiler: gcc
      env: PYTHON_EXECUTABLE=/usr/bin/python3
    - os : linux
      dist: trusty
      compiler: clang
      env:
        - PYTHON_EXECUTABLE=/usr/bin/python2
        - LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
    - os : linux
      dist: trusty
      compiler: gcc
      env: PYTHON_EXECUTABLE=/usr/bin/python2
    - os : linux
      dist: trusty
      compiler: clang
      env:
        - PYTHON_EXECUTABLE=/usr/bin/python2
        - LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
    - os : osx
      compiler: clang
      env:
        - CXX_COMPILER='clang++'
        - C_COMPILER='clang++'
        - Fortran_COMPILER='gfortran'
        - PYTHON_EXECUTABLE=/usr/bin/python
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      HOMEBREW_NO_AUTO_UPDATE=1 brew install swig;
      HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc || true;
      HOMEBREW_NO_AUTO_UPDATE=1 brew link --overwrite gcc;

    fi;

before_script:
  - mkdir build
  - cd build
  - |
    DATAFILE=$HOME/.cache/data.tar.gz
    if [ -f $DATAFILE ]; then
      cp $DATAFILE .
    fi
  - cmake .. -DENABLE_PYTHON=True -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE -DENABLE_TESTING=On
  - cp data.tar.gz $HOME/.cache
script:
  - VERBOSE=1 make
  - make test
after_failure:
  - cat Testing/Temporary/LastTest.log
after_success:
  - make doc
  - |
    if [ $TRAVIS_BRANCH = "master" ] && [ $TRAVIS_PULL_REQUEST = "false" ]; then
      openssl aes-256-cbc -K $encrypted_0581d1b3cf0a_key -iv $encrypted_0581d1b3cf0a_iv -in ../.travis/travis_deploy.enc -out travis_deploy -d
      chmod 600 travis_deploy
      eval "$(ssh-agent -s)"
      ssh-add travis_deploy
      cd html
      git init
      git checkout -b gh-pages
      git add .
      git -c user.name='travis' -c user.email='travis' commit -m `echo Build_$TRAVIS_COMMIT`
      git push -f --set-upstream git@github.com:CRPropa/CRPropa3.git gh-pages
    fi
