language: cpp

before_install:
<<<<<<< HEAD
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
=======
  - sudo apt-get add-apt-repository ppa:kubuntu-ppa/backports -y 
>>>>>>> 5422918b3089a7cacb323dfe2dcdff271936dde9
  - sudo apt-get update -qq
  - sudo apt-get install -qq swig gfortran libfftw3-dev libcfitsio3-dev libmuparser-dev python-dev python-numpy python3-dev cmake

compiler:
  - gcc
  - clang

env:
  - PYTHON_EXECUTABLE=/usr/bin/python3
  - PYTHON_EXECUTABLE=/usr/bin/python2

before_script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_PYTHON=True -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE -DENABLE_TESTING=On

script:
  - make
  - make test

after_failure:
  - cat Testing/Temporary/LastTest.log
