language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq swig gfortran libfftw3-dev libcfitsio3-dev libmuparser-dev python-dev python-numpy 

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_PYTHON=True

script: make
