language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq swig gfortran libfftw3-dev libcfitsio3-dev libmuparser-dev python-dev python-numpy python3-dev

compiler:
  - gcc
  - clang

env:
  - PYTHON_EXECUTABLE=/usr/bin/python3
  - PYTHON_EXECUTABLE=/usr/bin/python2

before_script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_PYTHON=True -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE -DENABLE_TESTING=On

script:
  - make
  - make test

after_failure:
  - cat Testing/Temporary/LastTest.log
