# FFTW_INCLUDE_DIR = fftw3.h
# FFTW_LIBRARIES = libfftw3.a
# FFTW_FOUND = true if FFTW3 is found

if(FFTW_INCLUDE_DIRS)
    find_path(FFTW_INCLUDE_DIR fftw3.h ${FFTW_INCLUDE_DIRS})
    find_library(FFTW_LIBRARY fftw3 ${FFTW_LIBRARY_DIRS})
else(FFTW_INCLUDE_DIRS)
    find_path(FFTW_INCLUDE_DIR fftw3.h ${QMC_INCLUDE_PATHS})
    find_library(FFTW_LIBRARIES fftw3 ${QMC_LIBRARY_PATHS})
endif(FFTW_INCLUDE_DIRS)

set(FFTW_FOUND FALSE)
if(FFTW_INCLUDE_DIR AND FFTW_LIBRARIES)
    set(FFTW_FOUND TRUE)
endif()

mark_as_advanced(
FFTW_INCLUDE_DIR
FFTW_LIBRARIES
FFTW_FOUND
)
