name: create-documentation
on: [workflow_dispatch]

jobs: 
  create-documentation: 
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "ubuntu-24"
            os: ubuntu-24.04
            swig_builtin: "On" 
            py: "/usr/bin/python3"
    # define steps to take
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prerequirements
        run: |
          sudo apt-get update
          sudo apt-get install libmuparser-dev libhdf5-serial-dev libomp5 libomp-dev libfftw3-dev libcfitsio-dev lcov doxygen graphviz
          sudo apt-get install pandoc # do not only use pip to install pandoc, see https://stackoverflow.com/questions/62398231/building-docs-fails-due-to-missing-pandoc
          pip install -r doc/pages/example_notebooks/requirements.txt # load requirements for notebooks
          pip install ninja sphinx==7.2.6 sphinx_rtd_theme m2r2 nbsphinx lxml_html_clean breathe pandoc exhale # load requirements for documentation
      - name: Set up the build
        run: |
          mkdir build
          cd build
          cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=$HOME/.local -DENABLE_PYTHON=True -DPython_EXECUTABLE=${{ matrix.config.py }} -DENABLE_TESTING=On -DENABLE_SWIG_BUILTIN=${{ matrix.config.swig_builtin }} -DSIMD_EXTENSIONS=native -DPython_INSTALL_PACKAGE_DIR=/home/runner/.local/ -DBUILD_DOC=On -DENABLE_COVERAGE=On
      - name: Build CRPropa
        run: |
          cd build
          cmake --build .
      - name: run test
        run: | 
          cd build
          ctest --output-on-failure --repeat until-pass:3
        continue-on-error: true
      - name: coverage report
        run: |
          cd build
          ninja coverage
      - name: build documentation
        run: |
          set -ex
          cd build
          cp -r ../doc doc-source
          cp -r xml doc-source/
          ninja doc
          cp -r coverageReport doc/pages/coverageReport
          tar -zcvf documentation.tar.gz doc  
      - name: archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: "documentation"
          path: | 
            build/documentation.tar.gz
