name: crpropa-testing
on: [push]

jobs:
  ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Preinstall
        run: |
          sudo apt-get update
          sudo apt-get install libmuparser-dev python3-dev python-numpy python3-setuptools libhdf5-serial-dev python3-matplotlib libiomp5 libiomp-dev libfftw3 libcfitsio
      - name: Set up the build
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_PYTHON=True -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE -DENABLE_TESTING=On
      - name: Build CRPropa
        run: |
          make
          make test
