name: crpropa-testing
on: [push]

jobs:
  test1:
    name: ${ { matrix.config.name } }
    runs-on: ${ { matrix.config.os } }
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest",
            os: ubuntu-latest,
            build_type: "Release", cc: "gcc", cxx: "g++", fc: "gfortran", 
            python_exe: "usr/bin/python3", swig_build_in: "ON"
          }
        - {
            name: "Ubuntu bionic beaver",
            os: ubuntu-18.04,
            build_type: "Release", cc: "gcc", cxx: "g++", fc: "gfortran", 
            python_exe: "usr/bin/python3", swig_build_in: "OFF"
          }
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Preinstall
        run: |
          sudo apt-get update
          sudo apt-get install libmuparser-dev python3-dev python-numpy python3-setuptools libhdf5-serial-dev python3-matplotlib libomp5 libomp-dev libfftw3-dev libcfitsio-dev
      - name: Set up the build
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_PYTHON=True -DPYTHON_EXECUTABLE=${ { matrix.config.python_exe } } -DENABLE_TESTING=On
      - name: Build CRPropa
        run: |
          make
          make test
